name: Scheduled Scraper

on:
  schedule:
    - cron: "30 2 * * *"   # 08:00 AM IST
    - cron: "30 3 * * *"   # 09:00 AM IST
    - cron: "30 4 * * *"   # 10:00 AM IST
    - cron: "30 6 * * *"   # 12:00 PM IST
    - cron: "30 8 * * *"   # 02:00 PM IST
    - cron: "30 10 * * *"  # 04:00 PM IST
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        run: node scraper.js
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
